name: Create Open VSX Namespace (One-time)

on:
  workflow_dispatch:

jobs:
  create-namespace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check if Namespace Already Exists
        run: |
          echo "🔍 Checking if namespace '${{ github.repository_owner }}' already exists..."
          
          # Install ovsx CLI
          npm install -g ovsx
          
          # Check if namespace exists
          if ovsx search --query "publisher:${{ github.repository_owner }}" | grep -q "${{ github.repository_owner }}"; then
            echo "✅ Namespace '${{ github.repository_owner }}' already exists in Open VSX Registry"
            echo "NAMESPACE_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Namespace '${{ github.repository_owner }}' does not exist"
            echo "NAMESPACE_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Open VSX Namespace
        if: steps.check_namespace.outputs.NAMESPACE_EXISTS != 'true'
        run: |
          echo "🏗️ Creating namespace '${{ github.repository_owner }}' in Open VSX Registry..."
          echo "This is a one-time setup step."
          echo ""
          echo "You'll need to:"
          echo "1. Have an Open VSX Registry account"
          echo "2. Be logged in to create the namespace"
          echo ""
          
          # Install ovsx CLI
          npm install -g ovsx
          
          # Create namespace using GitHub username
          ovsx create-namespace ${{ github.repository_owner }}
          
          if [ $? -eq 0 ]; then
            echo "✅ Namespace created successfully!"
            echo "You can now delete this workflow file."
          else
            echo "❌ Failed to create namespace"
            echo "Check your OVSX_PAT token and permissions"
            exit 1
          fi

      - name: Namespace Already Exists
        if: steps.check_namespace.outputs.NAMESPACE_EXISTS == 'true'
        run: |
          echo "✅ Namespace '${{ github.repository_owner }}' already exists!"
          echo "No action needed - you can now run the main publishing workflow."
          echo ""
          echo "You can delete this workflow file since the namespace is already created."
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
